begin;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000000001","app_metadata":{"role":"admin"}}',true);
do $$
declare club uuid; r uuid; h uuid; h2 uuid; hi2 uuid; ri uuid; hi uuid; org uuid; comp record; ident uuid; saved uuid; price integer; fee integer; n integer:=0; rejected boolean; aut bigint; req bigint; ev constant uuid:='b571f05e-ed23-4e07-929e-be2b73e601a5';
begin
 select count(*) into aut from public.entries where event_id='2af66251-66a2-4c51-8180-a5badf0584d4';
 select count(*) into req from public.reception_requests where event_id=ev;
 insert into public.fhs_roster_clubs(name) values('事前登録検証-'||gen_random_uuid()) returning id into club;
 insert into public.fhs_roster_entities(kind,name,jef_number) values('rider','事前検証選手','999999991') returning id into r;
 insert into public.fhs_roster_entities(kind,name,jef_number) values('horse','事前検証馬','999999992') returning id into h;
 insert into public.fhs_roster_affiliations(entity_id,club_id) values(r,club),(h,club);
 perform public.save_fhs_winter_participants(club,array[r,h],'{}');
 select rider_id into ri from public.fhs_winter_reception_roster where entity_id=r and club_id=club;
 select horse_id into hi from public.fhs_winter_reception_roster where entity_id=h and club_id=club;
 select organization_id into org from public.riders where id=ri;
 for comp in select * from public.competitions where event_id=ev order by id loop
  ident:=gen_random_uuid();price:=coalesce(comp.member_fee,comp.fee);
  saved:=public.register_winter_initial_entry(ident,org,comp.id,ri,hi,'member',false,true,price);
  if saved<>ident then raise exception 'Wrong ID';end if;
  if public.register_winter_initial_entry(ident,org,comp.id,ri,hi,'member',false,true,price)<>ident then raise exception 'Retry failure';end if;
  if not exists(select 1 from public.entries where id=ident and event_id=ev and start_order=1 and source='winter-initial') then raise exception 'Initial order or event incorrect';end if;
  if not exists(select 1 from public.reception_entries where entry_id=ident and event_id=ev and rider_id=ri and horse_id=hi and organization_id=org) then raise exception 'Entry missing from reception view';end if;
  if (select entry_fee from public.fhs_winter_initial_entries where id=ident)<>price then raise exception 'Fee incorrect';end if;
  rejected:=false;
  begin perform public.register_winter_initial_entry(gen_random_uuid(),org,comp.id,ri,hi,'member',false,true,price);exception when others then if sqlerrm not like '%登録済み%' then raise;end if;rejected:=true;end;
  if not rejected then raise exception 'Duplicate accepted';end if;
  n:=n+1;
 end loop;
 if n<>40 then raise exception 'Missing competitions';end if;
 select * into comp from public.competitions where event_id=ev and member_fee is not null and competition_no='5';
 rejected:=false;begin perform public.register_winter_initial_entry(gen_random_uuid(),org,comp.id,ri,hi,null,false,true,comp.member_fee);exception when others then if sqlerrm not like '%会員%' then raise;end if;rejected:=true;end;
 if not rejected then raise exception 'Membership omission accepted';end if;
 rejected:=false;begin perform public.register_winter_initial_entry(gen_random_uuid(),org,comp.id,ri,hi,'member',false,true,comp.member_fee+1);exception when others then if sqlerrm not like '%料金が更新%' then raise;end if;rejected:=true;end;
 if not rejected then raise exception 'Stale fee accepted';end if;
 select * into comp from public.competitions where event_id=ev and competition_no='8';
 rejected:=false;begin perform public.register_winter_initial_entry(gen_random_uuid(),org,comp.id,ri,hi,'member',false,false,coalesce(comp.member_fee,comp.fee));exception when others then if sqlerrm not like '%資格%' then raise;end if;rejected:=true;end;
 if not rejected then raise exception 'Unconfirmed qualification accepted';end if;
 select * into comp from public.competitions where event_id<>ev limit 1;
 rejected:=false;begin perform public.register_winter_initial_entry(gen_random_uuid(),org,comp.id,ri,hi,null,false,true,1000);exception when others then if sqlerrm not like '%Winterの競技%' then raise;end if;rejected:=true;end;
 if not rejected then raise exception 'Other event accepted';end if;
 insert into public.fhs_roster_entities(kind,name,jef_number) values('horse','事前検証馬2','999999993') returning id into h2;
 insert into public.fhs_roster_affiliations(entity_id,club_id) values(h2,club);
 perform public.save_fhs_winter_participants(club,array[r,h,h2],array[r,h]);
 select horse_id into hi2 from public.fhs_winter_reception_roster where entity_id=h2 and club_id=club;
 select * into comp from public.competitions where event_id=ev and competition_no='5';
 ident:=gen_random_uuid();perform public.register_winter_initial_entry(ident,org,comp.id,ri,hi2,'nonmember',false,true,comp.nonmember_fee);
 if (select entry_fee from public.fhs_winter_initial_entries where id=ident)<>comp.nonmember_fee or (select start_order from public.entries where id=ident)<>2 then raise exception 'Nonmember fee or append order incorrect';end if;
 select * into comp from public.competitions where event_id=ev and competition_no='1';
 ident:=gen_random_uuid();perform public.register_winter_initial_entry(ident,org,comp.id,ri,hi2,null,true,true,comp.op_fee);
 if not exists(select 1 from public.entries where id=ident and is_op) or (select entry_fee from public.fhs_winter_initial_entries where id=ident)<>comp.op_fee then raise exception 'OP fee incorrect';end if;
 select * into comp from public.competitions where event_id=ev and official limit 1;
 update public.horses set jef_registration_no=null where id=hi2;
 rejected:=false;begin perform public.register_winter_initial_entry(gen_random_uuid(),org,comp.id,ri,hi2,null,false,true,comp.fee);exception when others then if sqlerrm not like '%日馬連%' then raise;end if;rejected:=true;end;
 if not rejected then raise exception 'Official unregistered horse accepted';end if;
 if req<>(select count(*) from public.reception_requests where event_id=ev) then raise exception 'Registration created paid addition requests';end if;
 if aut<>(select count(*) from public.entries where event_id='2af66251-66a2-4c51-8180-a5badf0584d4') then raise exception 'Autumn changed';end if;
 perform set_config('request.jwt.claims','{"sub":"00000000-0000-0000-0000-000000000001","app_metadata":{"role":"user"}}',true);
 if exists(select 1 from public.fhs_winter_initial_entries) then raise exception 'Nonadmin ledger read';end if;
 rejected:=false;begin perform public.register_winter_initial_entry(gen_random_uuid(),org,comp.id,ri,hi,null,false,true,1000);exception when others then if sqlerrm not like '%本部ログイン%' then raise;end if;rejected:=true;end;
 if not rejected then raise exception 'Nonadmin write';end if;
end;$$;
rollback;
select 'PASS: 40 competitions, initial fee ledger, no added fees/applications, retry IDs, duplicates refused, membership/nonmember/OP/qualification/JEF/fee checks, append order, event isolation, admin-only; fixtures rolled back' as result;
