"use client"
import {useEffect,useRef,useState} from 'react'
import {verifyAdminSession,type AdminSession} from '@/lib/supabase-rest'
import {publishWinterMonitor,moveWinterEntry,saveWinterOrder,type WinterMonitorState} from '@/lib/winter-monitor'
import {WinterMonitorView} from './winter-monitor-view'
import {WinterTimetableEditor} from './winter-timetable-editor'
import {loadWinterRequests,type WinterRequestRow} from '@/lib/winter-reception'
import type {loadWinterData} from '@/lib/winter-data'
type Data=Awaited<ReturnType<typeof loadWinterData>>
const button='min-h-14 rounded-xl border-2 bg-blue-800 p-3 text-lg font-bold text-white disabled:opacity-50'
export function WinterStartList({data,session,onSession,onChanged}:{data:Data;session:AdminSession;onSession:(v:AdminSession)=>void;onChanged:()=>void}){
 const[compId,setCompId]=useState(''),[ids,setIds]=useState<string[]>([]),[page,setPage]=useState(0),[error,setError]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[requests,setRequests]=useState<WinterRequestRow[]>([])
 const[position,setPosition]=useState<{x:number;y:number}|null>(null),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null),lock=useRef(false)
 const competition=data.competitions.find(c=>c.id===compId)
 const original=data.entries.filter(e=>e.competition_id===compId&&!['wd','withdrawn'].includes(e.status.toLowerCase())).sort((a,b)=>a.start_order-b.start_order)
 const originalIds=original.map(e=>e.entry_id),originalKey=JSON.stringify(originalIds)
 const [baseline,setBaseline]=useState(originalKey)
 const stale=baseline!==originalKey
 const dirty=JSON.stringify(ids)!==originalKey
 useEffect(()=>{let active=true;loadWinterRequests(session.accessToken).then(rows=>{if(active)setRequests(rows)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'変更表示を取得できません')});return()=>{active=false}},[session.accessToken,data])
 function choose(id:string){if(dirty&&!window.confirm('未保存の並べ替えを破棄して競技を切り替えますか？'))return;setCompId(id);const rows=data.entries.filter(e=>e.competition_id===id&&!['wd','withdrawn'].includes(e.status.toLowerCase())).sort((a,b)=>a.start_order-b.start_order).map(e=>e.entry_id);setIds(rows);setBaseline(JSON.stringify(rows));setPage(0);setSaved('');setError('')}
 const timetable=data.timetable.find(row=>row.competition_id===compId)
 const monitor:WinterMonitorState|null=competition?{version:1,eventId:data.eventId,competitionId:competition.id,competitionNo:competition.competition_no,competitionName:competition.name,date:competition.competition_date,inspectionTime:timetable?.inspection_time,startTime:timetable?.start_time,timePhase:timetable?.phase,page,draft:dirty,updatedAt:new Date().toISOString(),rows:ids.map((id,index)=>{const e=data.entries.find(row=>row.entry_id===id);const q=requests.find(row=>row.status==='reflected'&&row.entry_id===id);return{id,number:index+1,rider:data.riders.find(r=>r.id===e?.rider_id)?.name??'要確認',horse:data.horses.find(h=>h.id===e?.horse_id)?.name??'要確認',organization:e?.organization_name??'要確認',isOp:!!e?.is_op,mark:q?.request_type==='add'?'追加':q?.request_type==='change'?'変更':''}})}:null
 // Publishing only on display changes avoids sending data on an idle timer.
 const displayKey=monitor?JSON.stringify({...monitor,updatedAt:''}):''
 useEffect(()=>{if(!monitor)return;try{publishWinterMonitor(monitor)}catch(reason){setError(reason instanceof Error?reason.message:'モニター送信に失敗しました')}},[displayKey])
 async function save(){if(lock.current||!competition||!ids.length||stale)return;lock.current=true;setBusy(true);setError('');try{const verified=await verifyAdminSession(session);onSession(verified);setSaved(await saveWinterOrder(competition.id,ids,original,verified.accessToken));setBaseline(JSON.stringify(ids));onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'保存できません')}finally{lock.current=false;setBusy(false)}}
 function move(from:string,to:string){if(busy||stale)return;setIds(value=>moveWinterEntry(value,from,to));setSaved('')}
 return <section className="space-y-4 rounded-xl border-2 border-blue-300 bg-white p-5"><h2 className="text-2xl font-bold">出番表の編集・モニター操作</h2><p>並べ替えは保存前からモニターに表示します。同じPC・同じブラウザーでモニターを開いてください。</p><label className="block text-xl">表示する競技<select className="mt-2 min-h-16 w-full rounded-xl border-2 p-3" value={compId} disabled={busy} onChange={e=>choose(e.target.value)}><option value="">競技を選択</option>{data.competitions.map(c=><option key={c.id} value={c.id}>第{c.competition_no}競技 {c.name}</option>)}</select></label>
 {error&&<p role="alert" className="bg-red-100 p-4 text-xl">{error}</p>}{stale&&<p className="bg-orange-100 p-4 text-xl">出番が更新されました。下の「最新の出番に戻す」で確認してから保存してください。</p>}
 {competition&&<><WinterTimetableEditor key={competition.id} competitionId={competition.id} initial={timetable??null} session={session} onSession={onSession} onChanged={onChanged}/><div className="flex flex-wrap gap-3"><a className={button} href="/winter/monitor" target="_blank" rel="noopener">モニター画面を開く</a><button className={button} disabled={busy||!ids.length||stale||!dirty} onClick={()=>void save()}>{busy?'保存中…':'出番表を保存'}</button><button className={button} disabled={busy} onClick={()=>{if(dirty&&!window.confirm('未保存の並べ替えを破棄しますか？'))return;setIds(originalIds);setBaseline(originalKey);setSaved('');onChanged()}}>最新の出番に戻す</button><button className={button} onClick={()=>setPosition({x:Math.max(0,window.innerWidth-430),y:100})}>小窓を端に表示</button></div><p role="status" className="text-xl">{saved?`保存日時：${new Date(saved).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})}`:dirty?'並べ替え中・未保存':'保存済みの順番を表示中'}</p>{!ids.length&&<p className="text-xl">上の「事前エントリーを出番表に登録」で人馬を登録すると編集できます。登録後は「最新の出番に戻す」で表示を更新してください。</p>}
 {ids.map((id,index)=>{const row=monitor!.rows[index];return <article key={id} draggable={!busy&&!stale} onDragStart={e=>e.dataTransfer.setData('text/plain',id)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=e.dataTransfer.getData('text/plain');if(ids.includes(from))move(from,id)}} className={`space-y-2 rounded-xl border-2 p-4 ${row.mark==='追加'?'bg-green-100':row.mark?'bg-orange-100':'bg-blue-50'}`}><p className="text-xl font-bold">{index+1}番 {row.isOp?'OP':''}　{row.rider} ／ {row.horse} {row.mark}</p><p>{row.organization}</p><div className="flex gap-3"><button className={button} disabled={busy||stale||index===0} onClick={()=>move(id,ids[index-1])}>↑ 前へ</button><button className={button} disabled={busy||stale||index===ids.length-1} onClick={()=>move(id,ids[index+1])}>↓ 次へ</button></div></article>})}
 {monitor&&<div className={position?'fixed z-40 w-[400px] max-w-[90vw] overflow-hidden rounded-xl border-2 border-blue-800 bg-white shadow-xl':'overflow-hidden rounded-xl border-2 border-blue-800'} style={position?{left:position.x,top:position.y}:undefined}><div className="flex touch-none items-center justify-between bg-blue-800 p-2 text-white" onPointerDown={e=>{if(!position||e.target!==e.currentTarget)return;drag.current={x:e.clientX,y:e.clientY,left:position.x,top:position.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current){const d=drag.current;setPosition({x:Math.max(0,Math.min(window.innerWidth-100,d.left+e.clientX-d.x)),y:Math.max(0,Math.min(window.innerHeight-60,d.top+e.clientY-d.y))})}}} onPointerUp={()=>{drag.current=null}} onPointerCancel={()=>{drag.current=null}}>表示プレビュー（ここを掴んで移動）<button onClick={()=>setPosition(position?null:{x:Math.max(0,window.innerWidth-430),y:100})}>{position?'元に戻す':'移動する'}</button></div><div className="max-h-[45vh] overflow-auto"><WinterMonitorView state={monitor} compact/></div><div className="flex justify-between p-2"><button className={button} disabled={page===0} onClick={()=>setPage(v=>v-1)}>前のページ</button><button className={button} disabled={(page+1)*30>=ids.length} onClick={()=>setPage(v=>v+1)}>次のページ</button></div></div>}
 </>}
 </section>
}
