"use client"
import {winterCompetitionLabel} from "@/lib/winter-display-order"
import {useRef,useState} from 'react'
import {verifyAdminSession,type AdminSession} from '@/lib/supabase-rest'
import {winterCompetition,type WinterFeeSelection} from '@/lib/winter-event'
import type {loadWinterData} from '@/lib/winter-data'
import {reviewWinterInitialEntry,saveWinterInitialEntry,UncertainInitialEntrySave,type WinterInitialEntryInput} from '@/lib/winter-initial-entry'
const field='mt-2 min-h-14 w-full rounded-xl border-2 p-3 text-xl'
const button='min-h-14 rounded-xl bg-blue-800 p-3 text-xl font-bold text-white disabled:opacity-50'
export function WinterInitialEntryRegistration({data,session,onChanged}:{data:Awaited<ReturnType<typeof loadWinterData>>;session:AdminSession;onChanged:()=>void}){
 const[orgId,setOrgId]=useState(''),[compId,setCompId]=useState(''),[riderId,setRiderId]=useState(''),[horseId,setHorseId]=useState(''),[selection,setSelection]=useState<WinterFeeSelection>({})
 const[review,setReview]=useState<WinterInitialEntryInput|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),lock=useRef(false)
 const org=data.organizations.find(x=>x.id===orgId),comp=data.competitions.find(x=>x.id===compId),rider=data.riders.find(x=>x.id===riderId),horse=data.horses.find(x=>x.id===horseId)
 function confirm(){setError('');setMessage('');try{if(!org||!comp||!rider||!horse)throw new Error('団体・競技・選手・馬を選択してください');const input={id:crypto.randomUUID(),organization:org,competition:comp,rider,horse,selection:{...selection}};reviewWinterInitialEntry(input);setReview(input)}catch(e){setError(e instanceof Error?e.message:'入力を確認してください')}}
 async function save(){if(!review||lock.current)return;lock.current=true;setBusy(true);setError('');try{const verified=await verifyAdminSession(session);await saveWinterInitialEntry(review,verified.accessToken);setMessage(`${review.rider.name} ／ ${review.horse.name} を第${review.competition.competition_no}競技の仮出番表に登録しました`);setUncertain(false);setReview(null);setRiderId('');setHorseId('');onChanged()}catch(e){setUncertain(e instanceof UncertainInitialEntrySave);setError(e instanceof Error?e.message:'保存できません')}finally{lock.current=false;setBusy(false)}}
 return <section className="space-y-4 rounded-xl border-2 border-blue-300 p-4"><h2 className="text-2xl font-bold">事前エントリーを出番表に登録</h2><p>参加名簿から人馬と競技を選び、仮出番表に登録します。追加手数料は付きません。締切後に出番を確認・並べ替えてください。</p>
 {!review?<fieldset disabled={busy} className="space-y-3">
 <label className="block text-xl">所属団体<select className={field} value={orgId} onChange={e=>{setOrgId(e.target.value);setRiderId('');setHorseId('')}}><option value="">団体を選択</option>{data.organizations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label className="block text-xl">登録する選手<select className={field} value={riderId} onChange={e=>setRiderId(e.target.value)}><option value="">選手を選択</option>{data.riders.filter(x=>x.organization_id===orgId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label className="block text-xl">登録する馬<select className={field} value={horseId} onChange={e=>setHorseId(e.target.value)}><option value="">馬を選択</option>{data.horses.filter(x=>x.organization_id===orgId).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label className="block text-xl">登録する競技<select className={field} value={compId} onChange={e=>{setCompId(e.target.value);setSelection({})}}><option value="">競技を選択</option>{data.competitions.map(x=><option key={x.id} value={x.id}>{winterCompetitionLabel(x)}</option>)}</select></label>
 {comp&&(comp.member_fee!==null||comp.nonmember_fee!==null)&&<label className="block text-xl">事前登録の料金区分<select className={field} value={selection.membership??''} onChange={e=>setSelection(v=>({...v,membership:e.target.value==='member'?'member':e.target.value==='nonmember'?'nonmember':undefined}))}><option value="">区分を選択</option><option value="member">会員</option><option value="nonmember">非会員</option></select></label>}
 {comp&&winterCompetition(comp.competition_no).instructorRequired&&<label className="flex items-center gap-3 text-xl"><input className="size-7" type="checkbox" checked={!!selection.instructorConfirmed} onChange={e=>setSelection(v=>({...v,instructorConfirmed:e.target.checked}))}/>地域乗馬指導者資格を確認しました</label>}
 {comp&&!comp.official&&comp.op_fee!==null&&<label className="flex items-center gap-3 text-xl"><input className="size-7" type="checkbox" checked={!!selection.isOp} onChange={e=>setSelection(v=>({...v,isOp:e.target.checked}))}/>OP参加</label>}
 <button type="button" className={button} disabled={!org||!comp||!rider||!horse} onClick={confirm}>事前エントリーの内容を確認</button>
 </fieldset>:<div className="space-y-3 rounded-xl bg-blue-50 p-4"><h3 className="text-2xl font-bold">この内容で出番表に登録します</h3><p className="text-xl">{review.organization.name}<br/>第{review.competition.competition_no}競技 {review.competition.name}<br/>{review.rider.name} ／ {review.horse.name}{review.selection.isOp?'（OP）':''}</p>{review.selection.membership&&<p>料金区分：{review.selection.membership==='member'?'会員':'非会員'}</p>}<p className="text-2xl font-bold">競技エントリー料 ¥{reviewWinterInitialEntry(review).entryFee.toLocaleString('ja-JP')}<small className="block text-lg">追加手数料 ¥0</small></p><p>競技料金の記録を保存します。入金済みにはしません。厩舎料等を含む団体の請求合計は別途確認します。</p><button className={button} type="button" disabled={busy} onClick={()=>void save()}>{busy?'登録中…':uncertain?'同じ内容で保存結果を再確認':'仮出番表に登録する'}</button><button type="button" className="ml-3 min-h-14 rounded-xl border-2 p-3 text-xl" disabled={busy||uncertain} onClick={()=>{setReview(null);setError('')}}>入力に戻る</button></div>}
 {error&&<p role="alert" className="rounded-xl bg-red-100 p-3 text-xl">{error}</p>}{message&&<p role="status" className="rounded-xl bg-green-100 p-3 text-xl">{message}</p>}
 </section>
}
