"use client"
import {useRef,useState} from 'react'
import type {WinterTimetableRow} from '@/lib/winter-data'
import {loadWinterData} from '@/lib/winter-data'
import {winterRpc} from '@/lib/winter-reception'
import {verifyAdminSession,type AdminSession} from '@/lib/supabase-rest'
export function WinterTimetableEditor({competitionId,initial,session,onSession,onChanged}:{competitionId:string;initial:WinterTimetableRow|null;session:AdminSession;onSession:(value:AdminSession)=>void;onChanged:()=>void}){
 const[expected,setExpected]=useState(initial),[inspection,setInspection]=useState(initial?.inspection_time??''),[start,setStart]=useState(initial?.start_time??''),[phase,setPhase]=useState<'provisional'|'final'>(initial?.phase??'provisional'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),lock=useRef(false)
 async function save(){if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{const verified=await verifyAdminSession(session);onSession(verified);const row=await winterRpc('save_winter_timetable',{p_competition_id:competitionId,p_inspection:inspection||null,p_start:start||null,p_phase:phase,p_expected:expected},verified.accessToken) as WinterTimetableRow;if(row?.competition_id!==competitionId)throw new Error('保存結果を確認できません');setExpected(row);setMessage('時間設定を保存しました');onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'保存できません')}finally{lock.current=false;setBusy(false)}}
 async function reload(){if(lock.current||!window.confirm('入力中の時間を破棄して最新の設定を読み込みますか？'))return;lock.current=true;setBusy(true);setError('');try{const data=await loadWinterData();const row=data.timetable.find(t=>t.competition_id===competitionId)??null;setExpected(row);setInspection(row?.inspection_time??'');setStart(row?.start_time??'');setPhase(row?.phase??'provisional');setMessage('最新の時間設定を読み込みました');onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'読み込めません')}finally{lock.current=false;setBusy(false)}}
 return <section className="space-y-3 rounded-xl border-2 bg-blue-50 p-4"><h3 className="text-xl font-bold">下見時間・開始時間</h3><p>コースデザイナー確認後に入力してください。未定は空欄にします。オープンチャットへの通知はこれまでどおり本部から行います。</p><label className="block text-xl">下見時間<input type="time" className="ml-3 min-h-14 rounded-xl border-2 p-3" value={inspection} disabled={busy} onChange={e=>setInspection(e.target.value)}/></label><label className="block text-xl">開始時間<input type="time" className="ml-3 min-h-14 rounded-xl border-2 p-3" value={start} disabled={busy} onChange={e=>setStart(e.target.value)}/></label><label className="block text-xl">表記<select className="ml-3 min-h-14 rounded-xl border-2 p-3" disabled={busy} value={phase} onChange={e=>setPhase(e.target.value==='final'?'final':'provisional')}><option value="provisional">予定</option><option value="final">確定</option></select></label><button className="min-h-14 rounded-xl bg-blue-800 p-3 text-xl font-bold text-white" disabled={busy} onClick={()=>void save()}>{busy?'保存中…':'時間を保存'}</button><button className="ml-3 min-h-14 rounded-xl border-2 p-3 text-xl" disabled={busy} onClick={()=>void reload()}>最新の時間を読み込む</button>{error&&<p role="alert" className="bg-red-100 p-3">{error}</p>}{message&&<p role="status">{message}</p>}</section>
}
