'use client'
import { useEffect, useState } from 'react'
import { ConfirmationPaper } from '@/components/self-settlement'
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, AUTUMN_EVENT_ID, verifyAdminSession, type AdminSession } from '@/lib/supabase-rest'
import { formatYen } from '@/lib/fees'
import type { selfSettlementAccount } from '@/lib/self-settlement-account'
type Row={id:string;organization_key:string;confirmed_by:string;payment_method:string;amount:number;created_at:string;document:ReturnType<typeof selfSettlementAccount>}
export function SelfSettlementHistory({session,orgId}:{session:AdminSession;orgId?:string}){
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);setError('');try{const verified=await verifyAdminSession(session);const response=await fetch(`${SUPABASE_URL}/rest/v1/self_settlement_confirmations?event_id=eq.${AUTUMN_EVENT_ID}${orgId?`&organization_key=eq.${encodeURIComponent(orgId)}`:''}&select=*&order=created_at.desc&limit=100`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${verified.accessToken}`},cache:'no-store'});if(!response.ok)throw new Error('選手の精算確定履歴を取得できません');setRows(await response.json())}catch(e){setError(e instanceof Error?e.message:'取得できません')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[orgId,session])
 useEffect(()=>{const finish=()=>{delete document.body.dataset.selfSettlementPrint};window.addEventListener('afterprint',finish);return()=>{window.removeEventListener('afterprint',finish);finish()}},[])
 function printSaved(){document.body.dataset.selfSettlementPrint='true';window.print()}
 return <><details className="print-hide rounded-xl border-2 border-blue-200 bg-blue-50 p-4"><summary className="cursor-pointer text-xl font-bold">選手が確定した精算内容（入金確認は別）</summary><p className="mt-3">支払い方法と明細の確認記録です。実際の入金は、本部の精算操作で確認・記録してください。</p><button type="button" disabled={busy} onClick={()=>void load()} className="my-3 min-h-12 rounded-lg border-2 bg-white px-4 font-bold">{busy?'読み込み中…':'確定履歴を更新'}</button>{error&&<p role="alert" className="text-red-700">{error}</p>}{rows.map(row=><div key={row.id} className="border-t py-3"><p className="font-bold">{row.document.document.organization} ／ {formatYen(row.amount)} ／ {row.document.document.method}</p><p>{new Date(row.created_at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo'})} ／ 確認者 {row.confirmed_by} ／ {row.id.slice(0,8).toUpperCase()}</p><button type="button" className="mt-2 min-h-10 rounded-lg border bg-white px-3 font-bold" onClick={()=>setSelected(row)}>確定時の精算書を確認・再印刷</button></div>)}{!busy&&!rows.length&&<p>確定履歴はありません。</p>}{selected&&<div className="mt-4 rounded-xl bg-white p-4"><div className="mb-3 flex gap-3"><button type="button" className="min-h-12 rounded-lg bg-blue-700 px-4 font-bold text-white" onClick={printSaved}>この精算書を印刷</button><button type="button" className="min-h-12 rounded-lg border px-4 font-bold" onClick={()=>setSelected(null)}>閉じる</button></div><ConfirmationPaper record={selected}/></div>}</details>{selected&&<div className="print-only self-settlement-confirmation document-page hidden"><ConfirmationPaper record={selected}/></div>}</>
}
